// app/guide/page.tsx의 불량 12종 데이터를 단일 소스로 추출 — guide 페이지 자체와
// /resins 상세 페이지(흔한 불량과 첫 점검 섹션의 역링크)가 공유. 내용은 원본과 동일(무변경 추출).
import type { DefectKey } from '@/lib/resin-kb';

export interface GuideDefect {
  id: string;
  nameKo: string; nameEn: string;
  descriptionKo: string; descriptionEn: string;
  causesKo: string[]; causesEn: string[];
  solutionsKo: string[]; solutionsEn: string[];
  resinNotesKo: Record<string, string>; resinNotesEn: Record<string, string>;
  color: string;
}

export const defects: GuideDefect[] = [
  {
    id: 'short-shot',
    nameKo: '미성형', nameEn: 'Short Shot',
    descriptionKo: '충전 부족으로 제품이 완성되지 않는 현상. 제품의 끝부분이나 얇은 부위가 채워지지 않음.',
    descriptionEn: 'Incomplete filling — the product is not fully formed. End sections or thin walls remain unfilled.',
    causesKo: ['사출 압력/속도 부족', '수지 온도 낮음 (점도 높음)', '게이트/러너 크기 부족', '벤트 불량 (공기 갇힘)', '계량 부족'],
    causesEn: ['Insufficient injection pressure/speed', 'Melt temperature too low (high viscosity)', 'Undersized gate or runner', 'Poor venting (trapped air)', 'Insufficient shot size (metering)'],
    solutionsKo: ['사출 압력 및 1차 속도 증가', '노즐/실린더 온도 상승', '게이트 크기 확대 또는 러너 개선', '벤트 추가/청소', '계량값 증가'],
    solutionsEn: ['Increase injection pressure and 1st-stage speed', 'Raise nozzle/barrel temperature', 'Enlarge gate or improve runner', 'Add or clean vents', 'Increase metering stroke'],
    resinNotesKo: { PA: '결정성 수지로 급격한 점도 변화. 온도 관리 중요.', PBT: '빠른 결정화. 게이트 크기 충분히 확보 필요.', PC: '고점도. 온도 충분히 높여야 함 (280-320℃).', ABS: '상대적으로 쉬운 편이나 온도 관리 필요.', LCP: '점도 매우 낮음. Short Shot 발생 드묾.' },
    resinNotesEn: { PA: 'Semi-crystalline: sharp viscosity change with temperature. Temperature control is critical.', PBT: 'Fast crystallization. Ensure adequate gate size.', PC: 'High viscosity. Requires high temperatures (280–320°C).', ABS: 'Relatively easy to process, but temperature management required.', LCP: 'Extremely low viscosity. Short shot is rare.' },
    color: 'red',
  },
  {
    id: 'flash',
    nameKo: '플래시', nameEn: 'Flash',
    descriptionKo: '파팅 라인이나 에젝터 핀 주변에서 수지가 새어 나오는 현상.',
    descriptionEn: 'Resin leaks past the parting line, ejector pins, or other mold interfaces.',
    causesKo: ['형체력 부족', '사출 압력/보압 과다', '금형 PL면 마모/손상', '금형 강성 부족', '수지 온도 과다 (점도 하락)'],
    causesEn: ['Insufficient clamp force', 'Excessive injection pressure or hold pressure', 'Worn or damaged parting line surface', 'Insufficient mold rigidity', 'Melt temperature too high (viscosity drops)'],
    solutionsKo: ['형체력 증가 또는 투영 면적 감소', '사출 압력/보압 감소', '금형 PL면 수리', '사출 속도 감소', '수지 온도 하강'],
    solutionsEn: ['Increase clamp force or reduce projected area', 'Reduce injection pressure and hold pressure', 'Repair parting line surface', 'Reduce injection speed', 'Lower melt temperature'],
    resinNotesKo: { PA: '점도 낮고 결정성 → Flash 발생 쉬움. 형체력 충분히 확보.', PPS: 'Flash 발생 매우 쉬움. 형체력 충분히 확보.', LCP: '점도 극히 낮음. Flash 발생 위험 최고. 금형 정밀도 중요.', PC: '고점도이나 온도 높으면 Flash 가능.', PP: '점도 낮음. Flash 주의.' },
    resinNotesEn: { PA: 'Low viscosity and semi-crystalline → prone to flash. Ensure sufficient clamp force.', PPS: 'Very flash-prone. Ensure sufficient clamp force.', LCP: 'Extremely low viscosity. Highest flash risk. Mold precision is critical.', PC: 'High viscosity, but flash possible at elevated temperatures.', PP: 'Low viscosity. Watch for flash.' },
    color: 'amber',
  },
  {
    id: 'sink-mark',
    nameKo: '싱크마크', nameEn: 'Sink Mark',
    descriptionKo: '두꺼운 부위 표면이 오목하게 함몰되는 현상. 내부 수축으로 발생.',
    descriptionEn: 'Concave depressions on the surface of thick sections, caused by internal shrinkage during cooling.',
    causesKo: ['보압 부족', '보압 시간 부족', '냉각 시간 부족', '게이트 크기 작음 (조기 동결)', '벽 두께 불균일'],
    causesEn: ['Insufficient hold pressure', 'Insufficient hold time', 'Insufficient cooling time', 'Small gate size (premature gate freeze)', 'Uneven wall thickness'],
    solutionsKo: ['보압 증가', '보압 시간 증가', '냉각 시간 증가', '게이트 크기 확대', '설계 변경 (벽 두께 균일화)'],
    solutionsEn: ['Increase hold pressure', 'Increase hold time', 'Increase cooling time', 'Enlarge gate size', 'Design change (uniform wall thickness)'],
    resinNotesKo: { PA: '수축률 높음. 보압 충분히 필요.', POM: '수축률 매우 높음 (2-3%). 보압 관리 중요.', PP: '수축률 높음 (1.5-2%). 냉각 충분히.', PC: '수축률 낮음. Sink Mark 상대적으로 적음.', PBT: 'GF 강화 시 수축률 감소.' },
    resinNotesEn: { PA: 'High shrinkage rate. Sufficient hold pressure required.', POM: 'Very high shrinkage (2–3%). Critical hold pressure management.', PP: 'High shrinkage (1.5–2%). Allow sufficient cooling.', PC: 'Low shrinkage. Sink marks relatively rare.', PBT: 'Shrinkage reduced with GF reinforcement.' },
    color: 'purple',
  },
  {
    id: 'weld-line',
    nameKo: '웰드라인', nameEn: 'Weld Line',
    descriptionKo: '두 수지 흐름이 합류하는 지점에 생기는 선. 강도 저하 원인.',
    descriptionEn: 'A line or seam that forms where two melt fronts meet. Can reduce structural strength.',
    causesKo: ['수지 온도 낮음', '금형 온도 낮음', '사출 속도 낮음', '게이트 위치 문제', '이형제 과다'],
    causesEn: ['Melt temperature too low', 'Mold temperature too low', 'Injection speed too low', 'Gate position problem', 'Excess mold release agent'],
    solutionsKo: ['수지 온도 상승', '금형 온도 상승', '사출 속도 증가', '게이트 위치/수 변경', '벤트 확인'],
    solutionsEn: ['Raise melt temperature', 'Raise mold temperature', 'Increase injection speed', 'Change gate location or add gates', 'Check and clean vents'],
    resinNotesKo: { 'GF강화': 'GF 강화재는 웰드라인 강도 극히 저하. 설계 단계에서 게이트 위치 검토.', PA66: '온도 범위 좁음. 충분한 온도 유지 중요.', PC: '고점도. 충분한 온도 필요.' },
    resinNotesEn: { 'GF Reinforced': 'GF reinforcement drastically reduces weld line strength. Review gate placement at design stage.', PA66: 'Narrow processing window. Maintaining sufficient temperature is critical.', PC: 'High viscosity. Adequate temperature is essential.' },
    color: 'blue',
  },
  {
    id: 'burn-mark',
    nameKo: '버닝/가스마크', nameEn: 'Burn Mark',
    descriptionKo: '공기 압축 발열 또는 수지 분해로 인해 제품에 탄 자국이 생기는 현상.',
    descriptionEn: 'Charring or discoloration from compressed-air combustion (diesel effect) or thermal degradation.',
    causesKo: ['사출 속도 과다 (공기 압축 발열)', '벤트 불량', '수지 온도 과다 (분해)', '과도한 체류 시간', '핫러너 온도 과다'],
    causesEn: ['Injection speed too high (compressed-air combustion)', 'Poor venting', 'Melt temperature too high (thermal degradation)', 'Excessive residence time', 'Hot runner temperature too high'],
    solutionsKo: ['사출 속도 감소', '벤트 추가/확대/청소', '수지 온도 하강', '사이클 타임 단축', '스크류 퍼지'],
    solutionsEn: ['Reduce injection speed', 'Add, enlarge, or clean vents', 'Lower melt temperature', 'Shorten cycle time', 'Purge screw'],
    resinNotesKo: { POM: '포름알데히드 가스 발생. 벤트 필수. 체류 시간 최소화.', PVC: 'HCl 가스 발생. 온도 관리 매우 중요.', PA: '수분에 의한 가스 발생 가능. 건조 중요.', ABS: '260℃ 이상에서 분해 시작.' },
    resinNotesEn: { POM: 'Generates formaldehyde gas. Venting is essential. Minimize residence time.', PVC: 'Generates HCl gas. Temperature control is critical.', PA: 'Moisture can generate gas. Drying is important.', ABS: 'Degradation begins above 260°C.' },
    color: 'red',
  },
  {
    id: 'silver-streak',
    nameKo: '은줄', nameEn: 'Silver Streak',
    descriptionKo: '게이트에서 수지 흐름 방향으로 은색 줄무늬가 생기는 현상. 수분 또는 가스 원인.',
    descriptionEn: 'Silver or streaky lines running in the flow direction from the gate, caused by moisture or gas.',
    causesKo: ['수지 건조 불충분 (수분)', '수지 온도 과다 (분해 가스)', '공기 혼입 (배압 낮음)', '스크류 역류', '이형제 가스'],
    causesEn: ['Insufficient resin drying (moisture)', 'Melt temperature too high (decomposition gas)', 'Air entrapment (back pressure too low)', 'Check ring backflow', 'Release agent outgassing'],
    solutionsKo: ['수지 건조 온도/시간 확인', '수지 온도 하강', '배압 증가', '스크류 RPM 감소', '사출 속도 감소 (1차)'],
    solutionsEn: ['Verify drying temperature and time', 'Lower melt temperature', 'Increase back pressure', 'Reduce screw RPM', 'Reduce 1st-stage injection speed'],
    resinNotesKo: { PA66: '수분 흡습 강함. 건조 필수 (80℃, 4-8시간).', PA6: '건조 80℃, 4-6시간.', PA46: '매우 흡습. 건조 80℃, 16-24시간.', PC: '건조 120℃, 4시간. 재건조 반드시 필요.', PMMA: '건조 80℃, 3시간.', TPU: '건조 80-100℃, 2-4시간.', PBT: '건조 120℃, 4시간.' },
    resinNotesEn: { PA66: 'Strong moisture absorption. Drying mandatory (80°C, 4–8 hrs).', PA6: 'Dry at 80°C, 4–6 hrs.', PA46: 'Extremely hygroscopic. Dry at 80°C, 16–24 hrs.', PC: 'Dry at 120°C, 4 hrs. Re-drying is essential.', PMMA: 'Dry at 80°C, 3 hrs.', TPU: 'Dry at 80–100°C, 2–4 hrs.', PBT: 'Dry at 120°C, 4 hrs.' },
    color: 'slate',
  },
  {
    id: 'discoloration',
    nameKo: '변색', nameEn: 'Discoloration',
    descriptionKo: '제품 색상이 의도와 다르게 변하는 현상. 갈색화, 황변, 탄화 등.',
    descriptionEn: 'Product color deviates from intent — browning, yellowing, charring, etc.',
    causesKo: ['수지 온도 과다 (열화)', '과도한 체류 시간', '이전 수지 오염', '스크류/바렐 손상', '난연제 분해'],
    causesEn: ['Melt temperature too high (thermal degradation)', 'Excessive residence time', 'Contamination from previous resin', 'Damaged screw or barrel', 'Flame retardant decomposition'],
    solutionsKo: ['수지 온도 하강', '사이클 타임 단축', '철저한 퍼지', '스크류/바렐 점검', '핫러너 온도 균일화'],
    solutionsEn: ['Lower melt temperature', 'Shorten cycle time', 'Thorough purging', 'Inspect screw and barrel', 'Equalize hot runner temperature'],
    resinNotesKo: { ABS: '260℃ 이상에서 황변/갈변.', '난연등급': '난연제 (특히 할로겐계) 분해온도 확인 필수.', PA: '수분에 의한 가수분해 변색.' },
    resinNotesEn: { ABS: 'Yellowing/browning above 260°C.', 'FR Grades': 'Check decomposition temperature of flame retardants (especially halogenated). Mandatory.', PA: 'Hydrolytic discoloration from moisture.' },
    color: 'amber',
  },
  {
    id: 'crack',
    nameKo: '크랙', nameEn: 'Crack',
    descriptionKo: '제품에 균열이 생기는 현상. 이형 시, 사용 중, 또는 후처리 중 발생.',
    descriptionEn: 'Cracks occurring during ejection, in service, or during post-processing.',
    causesKo: ['잔류 응력 과다 (보압 과다)', '이형 불량 (에젝터)', '금형 온도 낮음', '환경 응력 균열 (화학물질 접촉)', '과도한 사출 속도'],
    causesEn: ['Excessive residual stress (over-packing)', 'Ejection issues (ejector pin force)', 'Mold temperature too low', 'Environmental stress cracking (chemical contact)', 'Excessive injection speed'],
    solutionsKo: ['보압 감소', '에젝터 설계 개선, 이형제 적용', '금형 온도 상승', '냉각 시간 충분히', '잔류 응력 제거 어닐링'],
    solutionsEn: ['Reduce hold pressure', 'Improve ejector design; apply release agent', 'Raise mold temperature', 'Allow sufficient cooling time', 'Stress-relief annealing'],
    resinNotesKo: { PC: '환경 응력 균열 취약. 이형제 선택 주의.', PMMA: '취성. 잔류 응력 주의.', PA: '유리섬유 배향에 의한 방향성 균열.' },
    resinNotesEn: { PC: 'Susceptible to environmental stress cracking. Choose release agents carefully.', PMMA: 'Brittle material. Watch for residual stress.', PA: 'Directional cracking due to glass fiber orientation.' },
    color: 'red',
  },
  {
    id: 'warpage',
    nameKo: '휨/변형', nameEn: 'Warpage',
    descriptionKo: '이형 후 제품이 뒤틀리거나 변형되는 현상.',
    descriptionEn: 'Distortion or twisting of the part after ejection.',
    causesKo: ['불균일 냉각', '금형 온도 불균일', '보압 불균일 (멀티캐비티)', '수지 배향 차이 (GF 강화)', '두께 불균일'],
    causesEn: ['Uneven cooling', 'Non-uniform mold temperature', 'Uneven hold pressure (multi-cavity)', 'Differential fiber orientation (GF reinforced)', 'Non-uniform wall thickness'],
    solutionsKo: ['금형 냉각 회로 개선', '금형 온도 균일화', '보압 최적화', '냉각 지그 사용', '게이트 위치 변경'],
    solutionsEn: ['Improve mold cooling circuit', 'Equalize mold temperature', 'Optimize hold pressure', 'Use cooling fixtures', 'Change gate location'],
    resinNotesKo: { 'GF강화': '섬유 배향에 의한 이방성 수축 → 심한 휨. 설계 단계 검토 필수.', PP: '수축률 높음. 균일 냉각 중요.', PA: '흡습에 의한 치수 변화 고려.', POM: '높은 수축률. 충분한 보압/냉각.' },
    resinNotesEn: { 'GF Reinforced': 'Anisotropic shrinkage from fiber orientation → severe warpage. Review at design stage.', PP: 'High shrinkage. Uniform cooling is critical.', PA: 'Consider dimensional changes from moisture absorption.', POM: 'High shrinkage. Sufficient hold pressure and cooling required.' },
    color: 'purple',
  },
  {
    id: 'void',
    nameKo: '기포', nameEn: 'Void/Bubble',
    descriptionKo: '제품 내부에 생기는 공동(기포). 표면에서 보이지 않는 내부 불량.',
    descriptionEn: 'Internal voids inside the part that may not be visible from the surface.',
    causesKo: ['보압 부족', '보압 시간 부족', '게이트 조기 동결', '사출 속도 과다', '수지 건조 불량'],
    causesEn: ['Insufficient hold pressure', 'Insufficient hold time', 'Premature gate freeze', 'Injection speed too high', 'Inadequate resin drying'],
    solutionsKo: ['보압 증가', '보압 시간 증가', '게이트 크기 확대', '사출 속도 감소 (마지막 단계)', '수지 건조 확인'],
    solutionsEn: ['Increase hold pressure', 'Increase hold time', 'Enlarge gate size', 'Reduce injection speed (final stage)', 'Verify resin drying'],
    resinNotesKo: { PC: '두꺼운 부위 기포 발생 쉬움.', PA: '수분 기포 주의. 건조 필수.', '투명': '투명 수지에서 육안 확인 가능. 엄격한 관리 필요.' },
    resinNotesEn: { PC: 'Voids easily form in thick sections.', PA: 'Moisture-induced bubbles. Drying mandatory.', Transparent: 'Voids are visible in transparent resins. Strict control required.' },
    color: 'blue',
  },
  {
    id: 'jetting',
    nameKo: '젯팅', nameEn: 'Jetting',
    descriptionKo: '게이트에서 수지가 고속 분사되어 뱀 모양의 흔적이 생기는 현상.',
    descriptionEn: 'High-velocity melt jetting from the gate creates serpentine marks on the part surface.',
    causesKo: ['사출 속도 과다', '게이트 크기 작음', '게이트 위치 불량 (공간을 향해 직접 사출)', '수지 온도 낮음'],
    causesEn: ['Injection speed too high', 'Gate size too small', 'Poor gate location (direct injection into open space)', 'Melt temperature too low'],
    solutionsKo: ['사출 속도 감소 (1단)', '게이트 크기 확대', '게이트 위치/방향 변경', '수지 온도 상승', '다단 사출 (느리게 시작)'],
    solutionsEn: ['Reduce injection speed (1st stage)', 'Enlarge gate size', 'Change gate location or direction', 'Raise melt temperature', 'Multi-stage injection (start slow)'],
    resinNotesKo: { '일반': '게이트를 향해 벽면이 있으면 Jetting 억제.' },
    resinNotesEn: { General: 'Placing a wall opposite the gate suppresses jetting.' },
    color: 'amber',
  },
  {
    id: 'surface-roughness',
    nameKo: '표면 거침', nameEn: 'Surface Roughness',
    descriptionKo: '제품 표면이 거칠거나 광택이 없는 현상. 유동 불량, 금형 온도 부족 등.',
    descriptionEn: 'Rough surface or lack of gloss. Caused by inadequate flow, low mold temperature, etc.',
    causesKo: ['수지 온도 낮음', '금형 온도 낮음', '사출 속도 낮음', '금형 표면 불량', '이형제 과다'],
    causesEn: ['Melt temperature too low', 'Mold temperature too low', 'Injection speed too low', 'Poor mold surface condition', 'Excessive release agent'],
    solutionsKo: ['수지 온도 상승', '금형 온도 상승', '사출 속도 증가', '금형 폴리싱', '이형제 양 조절'],
    solutionsEn: ['Raise melt temperature', 'Raise mold temperature', 'Increase injection speed', 'Polish mold surface', 'Reduce release agent quantity'],
    resinNotesKo: { PA: 'GF 강화 시 표면에 섬유 노출 가능 → 금형 온도 높이면 개선.', PC: '광택 우수하나 금형 온도 중요.', ABS: '표면 재현성 양호.' },
    resinNotesEn: { PA: 'GF reinforcement can expose fibers at surface → raising mold temperature helps.', PC: 'Excellent surface gloss, but mold temperature is key.', ABS: 'Good surface reproducibility.' },
    color: 'slate',
  },
  {
    id: 'black-specks',
    nameKo: '흑점', nameEn: 'Black Specks',
    descriptionKo: '제품 표면이나 내부에 나타나는 검은 반점. 탄화된 수지 잔류물이나 이물 오염이 원인.',
    descriptionEn: 'Dark specks on or inside the part, caused by carbonized resin residue or contamination.',
    causesKo: ['이전 수지·색상 탄화 잔류 (퍼지 미흡)', '스크류·배럴·체크링 데드스페이스 탄화 축적', '수지 온도·체류시간 과다 (열분해)', '오염된 재생재·호퍼·주변 이물', '스크류/배럴 마모'],
    causesEn: ['Carbonized residue from previous resin/color (incomplete purge)', 'Carbon buildup in screw/barrel/check-ring dead spots', 'Melt temperature or residence time too high (thermal degradation)', 'Contaminated regrind, hopper, or environment', 'Worn screw or barrel'],
    solutionsKo: ['완전 퍼지 (전환 후 3~5샷 확인)', '스크류 인발 세척, 데드스페이스 적은 팁 검토', '수지 온도 하강·사이클 단축 (체류 감소)', '재생재·호퍼 청결 관리', '샷/배럴 용량 비율 확보'],
    solutionsEn: ['Purge thoroughly (verify over 3–5 shots after a changeover)', 'Pull and clean the screw; consider low-dead-space tips', 'Lower melt temperature and shorten cycle (reduce residence)', 'Keep regrind and hopper clean', 'Ensure adequate shot-to-barrel ratio'],
    resinNotesKo: { POM: '포름알데히드계 분해로 흑점·가스 발생 쉬움. 체류시간 최소화.', PVC: '열분해 민감. 온도·체류 엄격 관리.', '난연등급': '난연제 분해온도 확인. 체류 시 탄화 가중.' },
    resinNotesEn: { POM: 'Prone to specks/gas from formaldehyde-type degradation. Minimize residence time.', PVC: 'Sensitive to thermal degradation. Strict temperature and residence control.', 'FR Grades': 'Check flame-retardant decomposition temperature; carbonizes with long residence.' },
    color: 'slate',
  },
  {
    id: 'stringing',
    nameKo: '실끌림', nameEn: 'Stringing/Drooling',
    descriptionKo: '노즐에서 수지가 실처럼 늘어지거나(스트링), 개형 전 방울져 떨어지는(드룰링) 현상.',
    descriptionEn: 'Resin drawing into thin strings from the nozzle (stringing) or drooling as droplets before the mold opens.',
    causesKo: ['노즐 온도 과다', '감압(서크백) 부족', '수지 온도 과다', '노즐 오리피스 과대·마모', '노즐 팁 냉각 부족'],
    causesEn: ['Nozzle temperature too high', 'Insufficient decompression (suck-back)', 'Melt temperature too high', 'Nozzle orifice too large or worn', 'Insufficient nozzle-tip cooling'],
    solutionsKo: ['노즐 온도 하강', '감압(서크백) 증가', '수지 온도 하강', '역테이퍼 노즐·오리피스 크기 재검토', '노즐 팁 온도 프로파일 조정'],
    solutionsEn: ['Lower nozzle temperature', 'Increase decompression (suck-back)', 'Lower melt temperature', 'Review reverse-taper nozzle or orifice size', 'Adjust nozzle-tip temperature profile'],
    resinNotesKo: { PA: '저점도·결정성으로 드룰링 쉬움. 감압·노즐온도 관리.', PP: '저점도. 노즐온도 과다 주의.', PE: '저점도. 스트링 쉬움.' },
    resinNotesEn: { PA: 'Low viscosity and semi-crystalline → drools easily. Manage decompression and nozzle temp.', PP: 'Low viscosity. Watch for excessive nozzle temperature.', PE: 'Low viscosity. Prone to stringing.' },
    color: 'blue',
  },
  {
    id: 'gate-blush',
    nameKo: '게이트 블러시', nameEn: 'Gate Blush',
    descriptionKo: '게이트 바로 뒤 표면에 생기는 흐릿한 얼룩·광택 저하. 게이트 부위의 과도한 전단이 원인.',
    descriptionEn: 'A hazy, dull halo on the surface just past the gate, caused by excessive shear at the gate.',
    causesKo: ['게이트 부위 사출속도 과다 (과전단)', '게이트 과소 → 급속 감압', '금형 온도 낮음', '게이트 랜드 길이 과다', '밸브게이트 핀 마모·타이밍 불량 (핫러너)'],
    causesEn: ['Injection speed too high at the gate (over-shear)', 'Gate too small → rapid pressure drop', 'Mold temperature too low', 'Excessive gate land length', 'Valve-gate pin wear or timing issue (hot runner)'],
    solutionsKo: ['게이트 통과 구간 사출속도 감속 (다단 프로파일)', '게이트 확대, 랜드 길이 단축', '금형 온도 상승', '핫러너 게이트 온도 점검·상향', '(간헐·조건무효 시) 밸브핀 선단·스트로크 점검'],
    solutionsEn: ['Slow injection speed through the gate (multi-stage profile)', 'Enlarge the gate; shorten the land length', 'Raise mold temperature', 'Check and raise hot-runner gate temperature', 'If intermittent and process-independent, inspect valve-pin tip and stroke'],
    resinNotesKo: { '내열 ABS': '게이트 과전단에 민감. 속도 감속 우선.', PC: '고점도. 게이트 온도·속도 관리 중요.', 'PC/ABS': '게이트 블러시 흔함. 게이트 설계·속도 검토.' },
    resinNotesEn: { 'Heat-resistant ABS': 'Sensitive to gate over-shear. Slow the speed first.', PC: 'High viscosity. Gate temperature and speed control matter.', 'PC/ABS': 'Gate blush is common. Review gate design and speed.' },
    color: 'purple',
  },
  {
    id: 'delamination',
    nameKo: '박리', nameEn: 'Delamination',
    descriptionKo: '표면이 물고기 비늘처럼 층으로 벗겨지는 현상. 손톱으로 층이 떨어짐.',
    descriptionEn: 'The surface peels away in fish-scale layers; layers can be lifted with a fingernail.',
    causesKo: ['이종 수지 오염 (비상용 폴리머 혼입)', '이형제 과다', '수분·미건조 재료', '멜트·금형 온도 낮음 (층간 융착 불량)', '게이트 과전단'],
    causesEn: ['Contamination with incompatible resin', 'Excess mold release agent', 'Moisture or under-dried material', 'Melt or mold temperature too low (poor interlayer fusion)', 'Excessive shear at the gate'],
    solutionsKo: ['완전 퍼지·원료 검사 (DSC로 이종 피크 확인)', '이형제 최소화, 금형 청소', '재료 건조 확인', '멜트·금형 온도 상승', '사출속도 감소 (전단 완화)'],
    solutionsEn: ['Purge thoroughly and verify material (DSC for foreign peaks)', 'Minimize release agent; clean the mold', 'Verify material drying', 'Raise melt and mold temperature', 'Reduce injection speed (lower shear)'],
    resinNotesKo: { PP: '극성 수지(PA 등)와 혼입 시 박리 심함. 재생재 분리.', PA: 'PE/PP 혼입에 민감. 원료 관리 철저.', '재생재': '이종 혼입 최다 원인. 로트 분리·검사.' },
    resinNotesEn: { PP: 'Severe delamination if mixed with polar resins (e.g., PA). Segregate regrind.', PA: 'Sensitive to PE/PP contamination. Strict material control.', Regrind: 'Leading source of incompatible mixing. Segregate and inspect lots.' },
    color: 'amber',
  },
  {
    id: 'flow-mark',
    nameKo: '흐름자국', nameEn: 'Flow Mark',
    descriptionKo: '유동 방향을 따라 나타나는 물결·줄무늬 자국. 낮은 금형온도·사출속도가 주 원인.',
    descriptionEn: 'Wavy or streaky marks along the flow direction, mainly from low mold temperature or injection speed.',
    causesKo: ['금형 온도 과저 (특히 초기샷)', '사출 속도 과저', '멜트 온도 과저', '게이트·러너 유동 저항', '워밍업 부족'],
    causesEn: ['Mold temperature too low (especially early shots)', 'Injection speed too low', 'Melt temperature too low', 'Flow restriction at gate/runner', 'Insufficient warm-up'],
    solutionsKo: ['금형 온도 상승 (권장 범위 확보)', '사출 속도 증가', '멜트 온도 상승·사출압 증가', '게이트 확대 검토', '초기샷 워밍업 후 판정'],
    solutionsEn: ['Raise mold temperature (into recommended range)', 'Increase injection speed', 'Raise melt temperature and injection pressure', 'Consider enlarging the gate', 'Warm up before judging early shots'],
    resinNotesKo: { PP: '저금형온도서 물결 쉬움. 금형온도 확보.', ABS: '금형온도·속도로 개선 잘 됨.', PC: '고점도. 멜트·금형온도 충분히.' },
    resinNotesEn: { PP: 'Prone to waviness at low mold temperature. Secure mold temp.', ABS: 'Improves well with mold temperature and speed.', PC: 'High viscosity. Adequate melt and mold temperature.' },
    color: 'blue',
  },
  {
    id: 'tiger-stripe',
    nameKo: '타이거스트라이프', nameEn: 'Tiger Stripe',
    descriptionKo: '주로 PP·TPO에서 유동에 수직으로 나타나는 광택/무광 교대 밴드. 사출속도를 올리면 오히려 악화되는 것이 특징.',
    descriptionEn: 'Alternating glossy/matte bands perpendicular to flow, mostly in PP/TPO. Notably, raising injection speed makes it worse.',
    causesKo: ['PP 벽면 미끄럼(wall slip)·유동 불안정', '금형·멜트 온도 낮음', '사출 속도 과다 (밴드 악화)', '장거리 유동 (범퍼류)', '저유동(저MI) 재료 한계'],
    causesEn: ['PP wall slip and flow instability', 'Mold or melt temperature too low', 'Injection speed too high (worsens banding)', 'Long flow length (e.g., bumpers)', 'Low-flow (low-MI) material limitation'],
    solutionsKo: ['금형·멜트 온도 상승 (단일 최대 효과)', '사출 속도 하향·등속 프로파일 (★속도 상향 금지)', '고유동(고MI)·핵제 개질 그레이드 검토', '게이트 위치·유동길이 설계 재검토', '재료 기인 한계 인지'],
    solutionsEn: ['Raise mold and melt temperature (single biggest lever)', 'Lower injection speed; use a constant-speed profile (★ do NOT raise speed)', 'Consider high-flow (high-MI) or nucleated grades', 'Review gate location and flow length', 'Recognize material-driven limits'],
    resinNotesKo: { PP: '타이거스트라이프 대표 수지. 금형온도↑·감속이 핵심.', 'PP/EPDM': '범퍼·트림 다발. 유동길이·그레이드 검토.', TPO: '연질 PP 계열. 동일 대응.' },
    resinNotesEn: { PP: 'The classic tiger-stripe resin. Higher mold temp and slower speed are key.', 'PP/EPDM': 'Common in bumpers/trim. Review flow length and grade.', TPO: 'Soft PP-family. Same approach.' },
    color: 'amber',
  },
  {
    id: 'brittleness',
    nameKo: '취성', nameEn: 'Brittleness',
    descriptionKo: '제품이 충격에 쉽게 깨지거나 인장강도가 떨어지는 현상. 분자량 저하나 재료 문제가 흔한 원인.',
    descriptionEn: 'Parts crack easily under impact or show reduced strength, often from molecular-weight loss or material issues.',
    causesKo: ['과건조·과열로 분자량 저하 (열분해)', '재생재 비율 과다', '수분에 의한 가수분해 (PA·PC·PET)', '이종수지·오염 혼입', '용융·금형 온도 낮음 (웰드·층간 융착 불량)'],
    causesEn: ['Molecular-weight loss from over-drying or overheating (thermal degradation)', 'Excessive regrind ratio', 'Hydrolysis from moisture (PA, PC, PET)', 'Contamination with incompatible resin', 'Low melt/mold temperature (poor weld or interlayer fusion)'],
    solutionsKo: ['건조 조건 최적화 (과건조 금지)', '재생재 비율 감소, 버진 수지 비율↑', '가수분해성 수지는 규정대로 건조', '완전 퍼지·원료 검사', '용융·금형 온도 상승, 웰드라인 위치 재검토'],
    solutionsEn: ['Optimize drying (avoid over-drying)', 'Reduce regrind ratio; increase virgin resin', 'Dry hydrolysis-prone resins to spec', 'Purge thoroughly and inspect material', 'Raise melt/mold temperature; review weld-line placement'],
    resinNotesKo: { PC: '가수분해 취성. 건조 120℃·재건조 필수.', PA: '수분·과건조 양쪽에 민감. 규정 건조.', PET: '가수분해 심함. 저수분 건조 필수.' },
    resinNotesEn: { PC: 'Hydrolytic embrittlement. Dry at 120°C; re-drying mandatory.', PA: 'Sensitive to both moisture and over-drying. Dry to spec.', PET: 'Strong hydrolysis. Low-moisture drying essential.' },
    color: 'red',
  },
  {
    id: 'ejector-marks',
    nameKo: '이젝터 마크', nameEn: 'Ejector Marks',
    descriptionKo: '이젝터 핀 위치에 생기는 함몰·백화·자국. 이형 시 제품이 아직 무르거나 이형력이 과할 때 발생.',
    descriptionEn: 'Depressions, whitening, or marks at ejector-pin locations, from ejecting while the part is still soft or ejection force is too high.',
    causesKo: ['냉각 부족 (이형 시 제품 무름)', '이젝터 면적·개수 부족', '드래프트 각 부족', '보압 과다 (캐비티에 꽉 낌)', '금형 표면·언더컷 문제'],
    causesEn: ['Insufficient cooling (part too soft at ejection)', 'Insufficient ejector area or count', 'Inadequate draft angle', 'Excessive hold pressure (part gripping the cavity)', 'Mold surface or undercut issues'],
    solutionsKo: ['냉각 시간 증가', '이젝터 면적↑·균일 배치', '드래프트 각 확보', '보압 감소', '금형 연마, 언더컷 제거'],
    solutionsEn: ['Increase cooling time', 'Increase ejector area; distribute evenly', 'Add draft angle', 'Reduce hold pressure', 'Polish mold; remove undercuts'],
    resinNotesKo: { PP: '무른 상태 이형 쉬움. 냉각 확보.', PC: '이형력 크면 백화. 드래프트·연마 중요.', POM: '자기윤활성으로 이형 양호하나 냉각 관리.' },
    resinNotesEn: { PP: 'Ejects while soft easily. Secure cooling.', PC: 'Whitens under high ejection force. Draft and polish matter.', POM: 'Self-lubricating and ejects well, but manage cooling.' },
    color: 'slate',
  },
  {
    id: 'mold-deposit',
    nameKo: '금형 석출', nameEn: 'Mold Deposit (Plate-Out)',
    descriptionKo: '금형 표면에 백색·뿌연 잔류물이 쌓여 제품에 옮겨지는 현상(plate-out). 닦으면 옅어지는 것이 구조적 불량과의 결정적 차이.',
    descriptionEn: 'A white or hazy residue builds up on the mold surface and transfers to the part (plate-out). Unlike structural defects, it wipes off — that is the key tell.',
    causesKo: ['수지 휘발분·첨가제 석출 (plate-out)', '벤트 부족·막힘 → 가스 응축', '이형제 과다 전사', '용융 온도·체류시간 과다', '특정 캐비티 표면·데드스팟 정체'],
    causesEn: ['Volatiles/additives plating out from the resin', 'Poor or blocked venting → gas condensation', 'Excess mold-release transfer', 'Melt temperature or residence time too high', 'Dead-spot stagnation on specific cavity surfaces'],
    solutionsKo: ['금형 표면 주기적 세정', '벤트 추가·청소', '이형제 최소화', '용융 온도 하강·사이클(체류) 단축', '해당 캐비티 표면·핫러너 노즐 점검'],
    solutionsEn: ['Clean the mold surface periodically', 'Add or clean vents', 'Minimize release agent', 'Lower melt temperature; shorten cycle (residence)', 'Inspect the affected cavity surface and hot-runner nozzle'],
    resinNotesKo: { PVC: '활제·안정제 석출 다발. 벤트·세정 중요.', '난연등급': '난연제 휘발 석출. 온도·체류 관리.', POM: '포름알데히드계 석출·가스. 벤트 필수.' },
    resinNotesEn: { PVC: 'Lubricant/stabilizer plate-out common. Venting and cleaning matter.', 'FR Grades': 'Flame-retardant volatiles plate out. Manage temperature and residence.', POM: 'Formaldehyde-type deposits and gas. Venting essential.' },
    color: 'amber',
  },
  {
    id: 'color-streaks',
    nameKo: '색줄', nameEn: 'Color Streaks',
    descriptionKo: '안료·마스터배치 분산 불량으로 생기는 줄무늬·얼룩 색상. 이종수지 박리나 전체 변색과 구분.',
    descriptionEn: 'Streaky or marbled color from poor pigment/masterbatch dispersion. Distinct from delamination or overall discoloration.',
    causesKo: ['배압 부족 → 마스터배치 분산 불량', '스크루 전단·혼련 부족 (RPM 과저·체류 부족)', '마스터배치 캐리어 수지 불일치', '이종수지·오염 혼입', '마스터배치 비율 부적정'],
    causesEn: ['Low back pressure → poor masterbatch dispersion', 'Insufficient screw shear/mixing (low RPM, short residence)', 'Masterbatch carrier-resin mismatch', 'Contamination with incompatible resin', 'Incorrect masterbatch ratio'],
    solutionsKo: ['배압 단계적 상향 (혼련 개선)', '스크루 RPM·체류시간 조정 (혼련 확보)', '캐리어 수지 적합성 확인', '완전 퍼지·원료 검사', '마스터배치 비율·분산성 검토'],
    solutionsEn: ['Raise back pressure in steps (better mixing)', 'Adjust screw RPM/residence for mixing', 'Verify carrier-resin compatibility', 'Purge thoroughly; inspect material', 'Review masterbatch ratio and dispersibility'],
    resinNotesKo: { '메탈릭/펄': '★배압 대폭 상향 금지 — 알루미늄 플레이크 파단으로 광택 저하·회색화. 각도 의존 줄무늬면 분산 아닌 배향 문제.', 'GF강화': '배압↑ 시 섬유 파손 주의.', PP: '캐리어 불일치 흔함. 마스터배치 적합성 확인.' },
    resinNotesEn: { 'Metallic/Pearl': '★ Do NOT crank back pressure — it fractures aluminum flakes, dulling and graying the finish. If the streak is angle-dependent, it is orientation, not dispersion.', 'GF Reinforced': 'Watch for fiber breakage when raising back pressure.', PP: 'Carrier mismatch is common. Verify masterbatch compatibility.' },
    color: 'purple',
  },
  {
    id: 'dimensional-instability',
    nameKo: '치수 불안정', nameEn: 'Dimensional Instability',
    descriptionKo: '같은 조건인데 로트·캐비티·시간에 따라 치수가 변하는 현상. 형상이 변하는 휨(warpage)과 구분.',
    descriptionEn: 'Dimensions drift between lots, cavities, or over time under the same conditions. Distinct from warpage (shape change).',
    causesKo: ['결정성 수지 냉각·보압 변동', 'PA 흡습 팽창 (수분 1%≈치수 0.2~0.3%↑)', '측정 타이밍 불일치', '캐비티간 충전·냉각 편차', '후수축 (결정화 지속)'],
    causesEn: ['Cooling/hold variation in crystalline resins', 'Moisture expansion in PA (1% moisture ≈ 0.2–0.3% growth)', 'Inconsistent measurement timing', 'Cavity-to-cavity fill/cooling variation', 'Post-mold shrinkage (continued crystallization)'],
    solutionsKo: ['냉각 시간 증가·보압 안정화', '측정 타이밍 표준화 (이젝트 24h·65%RH 후)', 'PA는 어닐링으로 후수축 선처리', '캐비티 밸런스·냉각 회로 점검', '사이클 중량 ±0.5% 모니터'],
    solutionsEn: ['Increase cooling; stabilize hold pressure', 'Standardize measurement timing (after 24 h at 65% RH)', 'Anneal PA to pre-empt post-shrinkage', 'Check cavity balance and cooling circuits', 'Monitor shot weight within ±0.5%'],
    resinNotesKo: { PA: '★흡습으로 며칠에 걸쳐 치수 증가 — 공정 아닌 측정 타이밍·재료 문제. 성급한 조건 변경 보류.', POM: '높은 결정화·후수축. 냉각·어닐링.', PBT: '빠른 결정화. 게이트 동결·보압 관리.' },
    resinNotesEn: { PA: '★ Grows over days as it absorbs moisture — a measurement-timing/material issue, not a process knob. Hold off on hasty condition changes.', POM: 'High crystallinity and post-shrinkage. Cooling and annealing.', PBT: 'Fast crystallization. Manage gate freeze and hold.' },
    color: 'blue',
  },
  {
    id: 'sticking',
    nameKo: '이형 불량', nameEn: 'Sticking',
    descriptionKo: '제품이 캐비티나 코어에 붙어 정상적으로 이형되지 않는 현상.',
    descriptionEn: 'The part sticks to the cavity or core and does not release cleanly.',
    causesKo: ['드래프트 각 부족·언더컷', '보압 과다 (캐비티에 꽉 낌)', '금형 표면 거침·손상', '이형력·이형제 부족', '금형 온도 부적정'],
    causesEn: ['Insufficient draft or undercuts', 'Excessive hold pressure (part grips the cavity)', 'Rough or damaged mold surface', 'Insufficient ejection or release agent', 'Improper mold temperature'],
    solutionsKo: ['드래프트 각 확보, 언더컷 제거', '보압 감소', '금형 표면 연마 (유동 방향)', '이형제 적용·이젝터 점검', '금형 온도 조정'],
    solutionsEn: ['Add draft; remove undercuts', 'Reduce hold pressure', 'Polish mold surface (in the draw direction)', 'Apply release agent; check ejectors', 'Adjust mold temperature'],
    resinNotesKo: { PC: '점착성으로 코어에 붙기 쉬움. 드래프트·연마 중요.', TPU: '연질·점착. 이형제·냉각 관리.', PMMA: '표면 점착. 연마·이형 조건 관리.' },
    resinNotesEn: { PC: 'Tacky; tends to stick to the core. Draft and polish matter.', TPU: 'Soft and tacky. Manage release agent and cooling.', PMMA: 'Surface tack. Manage polish and release conditions.' },
    color: 'blue',
  },
];

// Brand-unified: all defect categories use the same brand color system
export const colorMap: Record<string, string> = {
  red:    'border-[var(--brand-border)] bg-brand-tint',
  amber:  'border-[var(--brand-border)] bg-brand-tint',
  purple: 'border-[var(--brand-border)] bg-brand-tint',
  blue:   'border-[var(--brand-border)] bg-brand-tint',
  slate:  'border-[var(--brand-border)] bg-brand-tint',
};

export const headerColorMap: Record<string, string> = {
  red:    'bg-brand',
  amber:  'bg-brand',
  purple: 'bg-brand',
  blue:   'bg-brand',
  slate:  'bg-brand',
};

export const DEFECT_NUMS: Record<string, string> = {
  'short-shot': '1', 'flash': '2', 'sink-mark': '3', 'weld-line': '4',
  'burn-mark': '5', 'silver-streak': '6', 'discoloration': '7', 'crack': '8',
  'warpage': '9', 'void': '10', 'jetting': '11', 'surface-roughness': '12',
  'black-specks': '13', 'stringing': '14', 'gate-blush': '15',
  'delamination': '16', 'flow-mark': '17', 'tiger-stripe': '18',
  'brittleness': '19', 'ejector-marks': '20', 'mold-deposit': '21',
  'color-streaks': '22', 'dimensional-instability': '23', 'sticking': '24',
};

// lib/resin-kb.ts DefectKey(underscore) → guide 페이지 id(dash) 매핑.
export const DEFECT_KEY_TO_GUIDE_ID: Partial<Record<DefectKey, string>> = {
  flash: 'flash',
  short_shot: 'short-shot',
  sink_mark: 'sink-mark',
  weld_line: 'weld-line',
  burn_mark: 'burn-mark',
  silver_streak: 'silver-streak',
  warpage: 'warpage',
  jetting: 'jetting',
  flow_mark: 'flow-mark',
};

export function getGuideDefectById(id: string): GuideDefect | undefined {
  return defects.find(d => d.id === id);
}
